version: '3.8'

services:
  # home:
  #   build: ./ܫܪܘܟܝܢ
  #   ports:
  #     - 8000:80

  assyrian-bible:
    build: ./assyrian-bible
    ports:
      - 8001:80

  # assyrian-transliterator:
  #   build: ./assyrian-transliterator
  #   ports:
  #     - 8002:80

  # assyrian-poem:
  #   build: ./assyrian-poem
  #   ports:
  #     - 8003:80

  # assyrian-english-dictionary:
  #   build: ./assyrian-english-dictionary
  #   ports:
  #     - 8004:80

  # assyrian-bible-study:
  #   build: ./assyrian-bible-study
  #   ports:
  #     - 8005:80
